### ISSUE TITLE
[BUG] Encrypt/decrypt XTEA just straight up is broken

### ISSUE THREAD

**Issue by hitman-resources** [glacier-modding/RPKG-Tool#25]
Don't forget tony

**To Reproduce**
Decrypt packagedefinition, change patchlevels to 10000, re-encrypt, watch as game does not work.

**Expected behavior**
I expected the feature to do what it says it does.

**Screenshots**
No.

**RPKG tool version:** [e.g. 2.14]
Apparently any version since the refactor

**Hitman Version:**
Any version

**Additional context**
Fix it bony

**Comment by RDIL** [comment]
Fixed on master, use nightly in the meantime.
