### ISSUE TITLE
[BUG] Mass Extract Not Operating as Expected

### ISSUE THREAD

**Issue by Juskelis** [glacier-modding/RPKG-Tool#37]
"Mass Extract -> Sounds (WWES) To OGG To IOI Paths From RPKGs In Folder" does not extract all the RPKGs in a folder

**To Reproduce**
1. In RPKG V2.17.3, select "Mass Extract -> Sounds (WWES) To OGG To IOI Paths From RPKGs In Folder"
2. In folder selector, navigate to Runtime folder and select it
3. In folder selector, navigate to output folder and select it
4. Wait for it to complete (took me about 9 hours with a slow hard drive)
5. In file explorer, navigate to output folder
6. Observe only some chunks are present (for me it was Chunk0, 1, 2.patch, and 15)
7. In RPGK, observe that _all_ chunks are present

**Expected behavior**
Should have folders for every chunk.

**Screenshots**
![image](https://user-images.githubusercontent.com/8293728/144284205-257ac82d-a043-489a-93c5-5537411b35a5.png)

**RPKG tool version:** 2.17.3

**Hitman Version:** epic

**Comment by Notexe** [comment]
You have to use the nightly version for now due to a change in the hash list for audio files: https://nightly.link/glacier-modding/RPKG-Tool/workflows/build/main/rpkg.zip

**Comment by Notexe** [comment]
Issue is fixed in the latest release v2.21.0
