### ISSUE TITLE
[BUG] Unable to Properly Edit Colors in Brick/Entity Editor 

### ISSUE THREAD

**Issue by HMBM47** [glacier-modding/RPKG-Tool#4]
**Describe the bug**
It has been brought to my attention some users aren't able to change the colors in the brick/entity editor. 

**To Reproduce**
1. Load all Runtime RPKGs
2. Search for 00AF710334C8F975.TEMP. head_shaman, in chunk9.
3. Right click, edit in Brick/Entity Editor.
4. In the left window, expand
5. Select Head_Shaman (4) (0)
6. According to one user, in the right window the colors Names are shown as "Weiß".
On my computer, where it works, these colors should read #FFC1C1D4 and a blue tint in the Preview window. 
7. The same user tries to edit the color, either by changing the Name # or picking a color. It will initially show the color they pick and the Name #, but once they click onto another setting the Preview becomes "x-ed out", and the Name becomes blank. 
(Shown in screenshot below)
8. If a package is compiled from this file, the game will show a pitch black texture.

**Expected behavior**
Being able to change colors in the brick/entity editor.

**Screenshots**
<a href="https://imgur.com/INumx8U"><img src="https://i.imgur.com/INumx8U.jpg" title="source: imgur.com" /></a>

**RPKG tool version:** 2.16.0

**Comment by AnthonyFuller** [comment]
Fixed in 02fd6fc you can use the `rpkg` artifact from the actions workflow [here](https://github.com/glacier-modding/RPKG-Tool/actions/runs/1108638986) until the next release.

Will close when an actual release has been made.

**Comment by HMBM47** [comment]
Fixed! :)
