### ISSUE TITLE
[BUG] Mass Extract issue with Hitman (2016) Steam edition

### ISSUE THREAD

**Issue by TomEvin** [glacier-modding/RPKG-Tool#41]
"Mass Extract issue with Hitman (2016) Steam edition"

**To Reproduce**
1. In RPKG V2.17.4, select "Mass Extract -> RTLV or LOCR"
2. In folder selector, navigate to Runtime folder and select it
3. In folder selector, navigate to output folder and select it
4. RTLV extraction crash the program, LOCR extraction stuck at dlc5.rpkg (timer stop, no crash, no freeze, can cancel)

**Expected behavior**
Should extract those files or show the content in Hex view.

**RPKG tool version:** 2.17.4

**Hitman Version:** 2016 (latest Steam)

**Additional context**
Manually select RTLV file in the tree view also crash the RPKG tool, LOCR dlc5.pkg or up throw an error.

System.Runtime.InteropServices.SEHException (0x80004005):
rpkg.MainWindow.generate_localization_string(String rpkg_file_name, String hash_string, String resource_type)
rpkg.MainWindow.MainTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
System.Windows.Forms.TreeView.WmNotify(Message& m)
System.Windows.Forms.TreeView.WndProc(Message& m)
System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by RDIL** [comment]
Is this issue reproducible on the latest nightly build?

**Comment by RDIL** [comment]
Closing due to lack of response.
