### ISSUE TITLE
[BUG] Mass WWEM extraction fails upon reaching certain file

### ISSUE THREAD

**Issue by cmathew** [glacier-modding/RPKG-Tool#43]
**Describe the bug**
rpkg-cli encounters an error when extracting certain sounds.

**To Reproduce**
1. Open a terminal in the rpkg-cli directory
2. Run something like: `rpkg-cli.exe -output_path "M:\Ambience\Hitman 3.100.0\Sources" -extract_wwem_to_ogg_from "G:\Epic Games\HITMAN3\Runtime"`
3. Wait a couple of minutes
4. Note error: `Error: wem file M:\Ambience\Hitman 3.100.0\Sources\WWEM\chunk0.rpkg\assembly\sound\wwise\originals\voices\unknown\play_sfx_setpiece_trap_electricity_waterpuddle_boilingwaterloop_4sec.wav].pc_wem\play_sfx_setpiece_trap_electricity_waterpuddle_boilingwaterloop_4sec.wav].pc_wem.wem could not be created.`

**Expected behavior**
All sounds extract without errors.

**Screenshots**
See attached [log.txt](https://github.com/glacier-modding/RPKG-Tool/files/7955080/log.txt). 

**RPKG tool version**: 2.18.0

**Hitman Version:** Hitman 3 Epic v3.100.0

**Additional context**
I tried using the GUI but the extraction process failed after a similar period of time. I also get a similar error when attempting WWES extraction: `Error: meta file M:\Ambience\Hitman 3.100.0\Sources\WWES\chunk0.rpkg\assembly\sound\wwise\originals\voices\english(us)\ai\gecko_maintenance_fch01\gen_grt47_gecko_maintenance_fch01\gen_grt47_mtnc_gecko_maintenance_fch01_gecko_maintenance_fch01_001.wav].pc_wes_009F9532CD4AC114.WWES could not be created.`

**Comment by Notexe** [comment]
Hey, can you try the latest release https://github.com/glacier-modding/RPKG-Tool/releases/tag/v2.21.0
The issue should be fixed in it.

**Comment by cmathew** [comment]
It works! Thank you so much for the investigation and update.
