### ISSUE TITLE
[BUG]Load REPO from Hitman 3 get crash

### ISSUE THREAD

**Issue by Dinozafre** [glacier-modding/RPKG-Tool#56]
**Describe the bug**
Crash program

**To Reproduce**
1. Start program.
2. Import RPKG folder (Hitman 3 files)
3. Go to REPO and click "load repo from loaded rpkgs"
4. Get crash

**Expected behavior**
Load repo and get crash.

**2.24.0** [e.g. 2.14]

**Hitman 3 (Epic, 1.120v)**

**Comment by AnthonyFuller** [comment]
Cannot reproduce. What folder are you importing?

**Comment by Notexe** [comment]
Do you have a modified repository? If so, maybe it's got some errors in it or something.

**Comment by Dinozafre** [comment]
> 
No, don't have modified repository

**Comment by Dinozafre** [comment]
> Cannot reproduce. What folder are you importing?

Hitman 3 EGS

**Comment by AnthonyFuller** [comment]
Are you importing the Runtime folder?

**Comment by Dinozafre** [comment]
> Are you importing the Runtime folder?

yes

**Comment by Dinozafre** [comment]
I found how this fix, just need delete chunk0patch300.rpkg
