### ISSUE TITLE
[BUG] Loading RPKGs fails

### ISSUE THREAD

**Issue by atampy25** [glacier-modding/RPKG-Tool#68]
**Describe the bug**
Loading RPKGs immediately crashes the (CLI) application. This is reproducible for all users if loading the dynamic resources RPKG, but for some users is reproducible for all RPKGs.

**To Reproduce**
- Be an affected user
- Load a certain RPKG

(can't be more specific)

**Expected behavior**
The CLI doesn't crash.

**RPKG tool version:** Issue introduced by c3910c729f6ef4eee853816b2a5fe603c3d4009a.

**Hitman Version:** H3, but not sure if this matters.

**Comment by Notexe** [comment]
The issue seems to be related to the filename's length (If it's 25 characters or more)
`randomname123456789123456.rpkg` will cause rpkg-cli to crash
while `randomname.rpkg` will work fine
