### ISSUE TITLE
Right click bug

### ISSUE THREAD

**Issue by mertkug** [glacier-modding/RPKG-Tool#7]
![image](https://user-images.githubusercontent.com/56736947/122640740-cf6efb80-d109-11eb-960c-e11f1f49f1b3.png)

Right click on rpkg tool bugged if you open all of game rpkg files. No extract menu shown.

**Comment by wefsda** [comment]
it happens for any rpkg file for me, and when i try to extract hash depends

**Comment by wefsda** [comment]
Found the solution: right click the other window and maximize it

**Comment by Notexe** [comment]
Should be fixed in the nightly build: https://nightly.link/glacier-modding/RPKG-Tool/workflows/build/main/rpkg.zip
(Please do not copy the ResourceLib DLLs from this download, use the preexisting ones from the release build of the RPKG Tool)
