### ISSUE TITLE
[BUG] Unable to build non-patch RPKGs

### ISSUE THREAD

**Issue by mike-koch** [glacier-modding/RPKG-Tool#73]
**Describe the bug**
When attempting to build a non-patch RPKG (such as rebuilding a dynamic resources RPKG), rpkg (and rpkg-cli) stops working after realizing that the `.meta` is not a patch file.

**To Reproduce**
1. Extract the latest dynamic resources RPKG from `%appdata%\Io Interactive\HITMAN3\TemporaryStorage`
2. Attempt to rebuild the RPKG, either via:
  a. RPKG's Generate > Generate RPKG From Folder menu
  b. `rpkg-cli`'s `-generate_rpkg_from` option
4. Observe that "RPKGv2 file [whatever the meta file was saved as].meta is not a patch file" is logged if using CLI, or observe that the progress bar in RPKG simply never goes away
5. Observe that RAM used by RPKG/`rpkg-cli` continues to increase until the application is forcibly closed.

**Expected behavior**
In RPKG v2.23, everything behaves as expected.  A RPKG is generated and is able to be read by the game.

**RPKG tool version:** Broken in 2.25 and 2.24, works in 2.23.

**Hitman Version:** H3

**Comment by AnthonyFuller** [comment]
This has been fixed in the latest nightly version.

It was to do with the filename being too long and it messing up the calculation for the dots causing the application to hang.

**Comment by RDIL** [comment]
Fixed by https://github.com/glacier-modding/RPKG-Tool/commit/d42c812d8bb1f93c168506403b3e181ec6d72794

**Comment by RDIL** [comment]
Correction: fixed by https://github.com/glacier-modding/RPKG-Tool/commit/39af95fab1959d5260dcc2563df7d21fdecc4708
