### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Ygerna** [glacier-modding/RPKG-Tool#8]
When I click on the RPKG tool execute, it immediately crashes saying it stopped working. When I click the other execute, windows says it misses Kernel32.DLL. Please don't tell me the tool is not supported for Windows 7 because I tried installing windows 10 for like 20 times and I can't just get it to work for unknown reasons :'(

**Comment by AnthonyFuller** [comment]
Unfortunately RPKG does not work on Windows 7. It is known to work for Windows 10.
I doubt support will ever be sought out as Windows 7 has gone [past it's end of life by Microsoft](https://www.microsoft.com/en-gb/windows/windows-7-end-of-life-support-information).

Closing issue.
