### ISSUE TITLE
I cannot find subtitles for some cinematic video

### ISSUE THREAD

**Issue by D-LUFFY89** [glacier-modding/RPKG-Tool#97]
I extracted all the files with text subtitles and did not find the subtitles I was looking for

RTLV & DLGE & LOCR

Started from

"END OF THE LINE"

Some texts from the game

```
She came home.
Carlisle's lost an empire.
You fall hard enough
and you tend to be reminded of what truly matters.
```
From minute 2:00
https://youtu.be/4ZcJr3-J74A?si=-NeTfj7xyFTAZ-dn&t=121

**Comment by AnthonyFuller** [comment]
It is in `chunk3` (and any subsequent patches where it may have been modified) in a RTLV file with the hash `00760C2E381D4072`. Ensure the tool is updated tot he latest version.

**Comment by D-LUFFY89** [comment]
Thanks, I found what I was looking for
